services:
  karl-vk-admin:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: karl-vk-admin
    ports: 
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
    command: > 
      gunicorn core.project.wsgi:application
      --bind 0.0.0.0:${DJANGO_PORT:-8000}
      --workers 1
      --worker-class gthread
      --threads 2
      --timeout 60
      --log-level info
    env_file:
      - ../.env
    volumes:
      - ..:/app/