# Generated by Django 6.0.3 on 2026-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('vk_id', models.BigIntegerField(blank=True, null=True, verbose_name='VK ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя пользователя')),
                ('thread_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='THREAD ID')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'constraints': [models.UniqueConstraint(condition=models.Q(('vk_id__isnull', False)), fields=('vk_id',), name='unique_vk_id_not_null'), models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_not_null'), models.UniqueConstraint(condition=models.Q(('thread_id__isnull', False)), fields=('thread_id',), name='unique_thread_id_not_null')],
            },
        ),
    ]
