# Generated by Django 6.0.3 on 2026-03-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID чата')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название чата')),
                ('type_chat', models.CharField(choices=[('GROUP', 'Групповой'), ('PRIVATE', 'Приватный')], max_length=10)),
                ('is_active', models.BooleanField(default=False, verbose_name='Разрешение')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Запрос пользователя')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ нейрокуратора')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message', to='chats.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_message', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
